#import "../../../components/Recommendation.gql"
#import "../../../components/Profile.gql"

query GetProfile($username: String!) {
  advisors {
    profile(username: $username) {
      ...ProfileInformation
    }
  }
}
