mutation RespondRequest($request: String!, $file: Upload, $response: AdvisorsJSONObject) {
  advisors {
    respondRequest(request: $request, file: $file, response: $response)
  }
}

query GetRequest ($request: String!) {
  advisors {
    getRequestAssignment(request: $request) {
      request {
        givenName
        familyName
        email
        type
        resumeUrl
      }
      response
      responseFile
    }
  }
}
